### ISSUE TITLE
Suspension on combine

### ISSUE THREAD

**Issue by VenoushCZ** [JanCraymer/FS22_HeadtrackingCameraSuspension#1]
Hi! I tested this MOD https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=232414&title=fs2022 and it seams that the HeadtrackingCameraSuspension is not active in it. Please can you explain if it is a bug or a feature?
Thank you for your work!

**Comment by JanCraymer** [comment]
Hello VenoushCZ,

thanks for letting me know of this issue. Unfortunately there is not much I can do about it as it is a problem within the modded combine. To make the camera suspension work there must be a reference to a suspension node (suspensionNodeIndex) within the indoorCamera-Node in the mods XML file. It seems that the mod (and some other mods I checked) is missing that reference.

This means that not only the headtracking camera suspension doesn't work but also the camera suspension without headtracking won't work. I suggest to contact the modder of the combine and let him know of this issue.

Kind regards,
Jan

**Comment by VenoushCZ** [comment]
Hi Jan,

Thank you for clearing it up! I will take a look at mods where it works and compare it with this one and I add the reference.

V.
