### ISSUE TITLE
Any Chance for a new Version?

### ISSUE THREAD

**Issue by GrandSurf** [JanCraymer/FS22_HeadtrackingCameraSuspension#4]
Dont work with new LS Version!

**Comment by JanCraymer** [comment]
Hello, do you mean version 1.7.1 which was released on September 6th?

I've played that version a couple of hours without any issues. 

Doesn't it work for you at all or just a specific vehicle?

I know of some vehicles that haven't been properly converted from older FS versions that don't have camera suspension even without headtracking. Maybe you got one of those?

Do you have any errors in the log?

**Comment by GrandSurf** [comment]
Problem found - no "suspensionNodeIndex" entry in the .xml of any mods. Have fix it with corresponding entry in the xml's. Thanks...

**Comment by JanCraymer** [comment]
I'm glad you found the problem :)
