### ISSUE TITLE
Mod does not work

### ISSUE THREAD

**Issue by Fabian19747383** [JanCraymer/FS22_HeadtrackingCameraSuspension#5]
Hallo,

I Played yesterday with the newest Patch. This mod is not Working for With this patch.  Is there any chance to update IT?

**Comment by JanCraymer** [comment]
Hello Fabian,

I just tested it myself and it still works for me. Does it not work at all or just with specific vehicles? Do you have any errors in your log file? Also please make sure you're using the latest version of the script.

https://github.com/JanCraymer/FS22_HeadtrackingCameraSuspension/releases/tag/v1.1.0.0

**Comment by Fabian19747383** [comment]
Hello Jan,

 

thanks for your answer. I downloaded the .zip file from the newest version and than i copy the .zip file in the mods folder. It dont works for me. If i turn off the TrackIR5 system its normal. If i turn on the TrackIR5 it dont works.

 

Gesendet: Mittwoch, 16. November 2022 um 17:43 Uhr
Von: "Jan" ***@***.***>
An: "JanCraymer/FS22_HeadtrackingCameraSuspension" ***@***.***>
Cc: "Fabian19747383" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [JanCraymer/FS22_HeadtrackingCameraSuspension] Mod does not work (Issue #5)


 

Hello Fabian,

I just tested it myself and it still works for me. Does it not work at all or just with specific vehicles? Do you have any errors in your log file? Also please make sure you're using the latest version of the script.

https://github.com/JanCraymer/FS22_HeadtrackingCameraSuspension/releases/tag/v1.1.0.0

**Comment by JanCraymer** [comment]
Hello Fabian,

just to be sure, can you see the mod in the mod list before starting your savegame?

**Comment by Fabian19747383** [comment]
Hello Jan,

 

yes it is in the modlist.

 
 

Gesendet: Donnerstag, 17. November 2022 um 18:46 Uhr
Von: "Jan" ***@***.***>
An: "JanCraymer/FS22_HeadtrackingCameraSuspension" ***@***.***>
Cc: "Fabian19747383" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [JanCraymer/FS22_HeadtrackingCameraSuspension] Mod does not work (Issue #5)


 

Hello Fabian,

just to be sure, can you see the mod in the mod list before starting your savegame?

**Comment by JanCraymer** [comment]
Hey Fabian,

can you please try a new savegame with only the script and no other mods, so we can rule out any mod conflicts?

**Comment by Fabian19747383** [comment]
Hi Jan,

 

i tried it without any other mods. it does not work. you can watch any video of "AgrarPlay". He uses the TrackIR5 too.

It does not work for him too.

 
 

Gesendet: Freitag, 18. November 2022 um 12:48 Uhr
Von: "Jan" ***@***.***>
An: "JanCraymer/FS22_HeadtrackingCameraSuspension" ***@***.***>
Cc: "Fabian19747383" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [JanCraymer/FS22_HeadtrackingCameraSuspension] Mod does not work (Issue #5)


 

Hey Fabian,

can you please try a new savegame with only the script and no other mods, so we can rule out any mod conflicts?

**Comment by JanCraymer** [comment]
Hello Fabian,

I still have no idea what might be the problem in your case. Please try the new version and report back if it works for you or not.
Do you own any DLC? If yes, which ones?

Du kannst auch in Deutsch antworten, falls dir das lieber ist ;-)

https://github.com/JanCraymer/FS22_HeadtrackingCameraSuspension/releases/tag/v1.1.1.0

**Comment by Fabian19747383** [comment]
Hallo Jan,

 

wenn ich das schon vorher gewusst hätte, dann hätte ich nicht mein schlechtes Englisch verwenden müssen!

Naja. Verstanden haben wir uns ja einigermaßen. Danke dir. Ich werde die neue Version heute Abend gleich testen.

Ich melde mich dann nochmal.

 
 

Gesendet: Dienstag, 22. November 2022 um 22:03 Uhr
Von: "Jan" ***@***.***>
An: "JanCraymer/FS22_HeadtrackingCameraSuspension" ***@***.***>
Cc: "Fabian19747383" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [JanCraymer/FS22_HeadtrackingCameraSuspension] Mod does not work (Issue #5)


 

Hello Fabian,

I still have no idea what might be the problem in your case. Please try the new version and report back if it works for you or not.
Do you own any DLC? If yes, which ones?

Du kannst auch in Deutsch antworten, falls dir das lieber ist ;-)

https://github.com/JanCraymer/FS22_HeadtrackingCameraSuspension/releases/tag/v1.1.1.0

**Comment by Fabian19747383** [comment]
Hallo Jan,

 

also es hat bei mir leider nicht funktioniert. Kann ich dir irgendwie zwei Clips senden? Einen ohne Headtrack System und einen mit?
Wenn du Lust hast, kannst du dir ja mal einen kurzen Ausschnitt von Agrarplay auf Youtube anschauen. Der hat das gleiche Problem.

 
 

Gesendet: Dienstag, 22. November 2022 um 22:03 Uhr
Von: "Jan" ***@***.***>
An: "JanCraymer/FS22_HeadtrackingCameraSuspension" ***@***.***>
Cc: "Fabian19747383" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [JanCraymer/FS22_HeadtrackingCameraSuspension] Mod does not work (Issue #5)


 

Hello Fabian,

I still have no idea what might be the problem in your case. Please try the new version and report back if it works for you or not.
Do you own any DLC? If yes, which ones?

Du kannst auch in Deutsch antworten, falls dir das lieber ist ;-)

https://github.com/JanCraymer/FS22_HeadtrackingCameraSuspension/releases/tag/v1.1.1.0

**Comment by JanCraymer** [comment]
Also ich glaube dir, dass du das Problem hast. Ich habe auch AgrarPlay schon gefragt, was bei ihm besonders sein könnte. 

Ich kann nur leider kein Problem beheben, welches ich bei mir nicht nachstellen kann.

Spielst du lokal oder auf einem Dedi? Falls Dedi, dann probiere bitte mal ein lokales Savegame. Das wäre jetzt das einzige, was ich mir noch vorstellen könnte.

**Comment by Fabian19747383** [comment]
Hmm. Ich spiele nur auf lokalen Savegames. Könntest du eventuell etwas mit LOG Dateien anfangen? Wenn ja welche?

 
 

Gesendet: Donnerstag, 24. November 2022 um 19:25 Uhr
Von: "Jan" ***@***.***>
An: "JanCraymer/FS22_HeadtrackingCameraSuspension" ***@***.***>
Cc: "Fabian19747383" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [JanCraymer/FS22_HeadtrackingCameraSuspension] Mod does not work (Issue #5)


 

Also ich glaube dir, dass du das Problem hast. Ich habe auch AgrarPlay schon gefragt, was bei ihm besonders sein könnte.

Ich kann nur leider kein Problem beheben, welches ich bei mir nicht nachstellen kann.

Spielst du lokal oder auf einem Dedi? Falls Dedi, dann probiere bitte mal ein lokales Savegame. Das wäre jetzt das einzige, was ich mir noch vorstellen könnte.

**Comment by JanCraymer** [comment]
Hi Fabian,

ja, du könntest mal deine Log-Datei anhängen, vielleicht steht da was dran.
Und jetzt noch eine blöde Frage: kannst du bitte mal in den Einstellungen prüfen, ob die Kamerafederung auch aktiviert ist? Vielleicht hat sich das durch das Update verstellt, oder so.

**Comment by JanCraymer** [comment]
Da keine weitere Rückmeldung, gehe ich mal davon aus, das Problem hat sich erledigt.
